<a href="https://colab.research.google.com/github/denverkim/DM_FALL2026/blob/main/DM26_LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 고객데이터 분석 실습

In [4]:
# Import XLMD_Customer.xls and create queries to answer the following questions: xlmd_customer 파일을 임포트한 후에 다음 질문에 답하시오
import pandas as pd

customer = pd.read_excel('/content/xlmd_customer.xls', header=1)
customer

,CUST ID,REGION,RENT VS. OWN,NUM HOUSEHOLD,ANNUAL INCOME,TOTAL PURCHASES,NUM PURCHASES
0,1,North,Own,1,10K-25K,38,1
1,2,South,Own,4,100K+,30,4
2,3,North,Rent,3,25K-50K,19,3
3,4,West,Own,5,25K-50K,21,6
4,5,East,Own,6,50K-100K,35,7
...,...,...,...,...,...,...,...
482,483,South,Rent,2,50K-100K,97,4
483,484,North,Own,1,25K-50K,61,6
484,485,East,Rent,3,50K-100K,75,5
485,486,East,Own,6,50K-100K,76,9
486,487,West,Own,4,50K-100K,98,2

In [6]:
# 전처리
customer = customer.set_index('CUST ID')
customer

,REGION,RENT VS. OWN,NUM HOUSEHOLD,ANNUAL INCOME,TOTAL PURCHASES,NUM PURCHASES
CUST ID,,,,,,
1,North,Own,1,10K-25K,38,1
2,South,Own,4,100K+,30,4
3,North,Rent,3,25K-50K,19,3
4,West,Own,5,25K-50K,21,6
5,East,Own,6,50K-100K,35,7
...,...,...,...,...,...,...
483,South,Rent,2,50K-100K,97,4
484,North,Own,1,25K-50K,61,6
485,East,Rent,3,50K-100K,75,5
486,East,Own,6,50K-100K,76,9
487,West,Own,4,50K-100K,98,2

In [9]:
# Q1. Open Show all information for only customers who live in the North region. 북쪽에 사는 고객들의 정보를 보여주시오
customer[customer['REGION'] == 'North']

,REGION,RENT VS. OWN,NUM HOUSEHOLD,ANNUAL INCOME,TOTAL PURCHASES,NUM PURCHASES
CUST ID,,,,,,
1,North,Own,1,10K-25K,38,1
3,North,Rent,3,25K-50K,19,3
9,North,Own,5,50K-100K,30,8
11,North,Own,1,50K-100K,21,4
17,North,Own,6,50K-100K,129,5
...,...,...,...,...,...,...
468,North,Rent,2,50K-100K,119,3
469,North,Own,6,10K-25K,185,6
477,North,Own,2,25K-50K,59,4
479,North,Rent,5,100K+,60,8
484,North,Own,1,25K-50K,61,6

In [11]:
customer.columns

Index(['REGION', 'RENT VS. OWN', 'NUM HOUSEHOLD', 'ANNUAL INCOME',
       'TOTAL PURCHASES', 'NUM PURCHASES'],
      dtype='object')

In [15]:
# Q2. Show all information for only customers who (a) live in the North region, (b) own their homes, and (c) have only one household member. 북쪽에 살면서 자기집을 소유하고, 1명의 가정구성원을 가진 고객의 정보를 보여주시오.
customer[(customer['REGION'] == 'North') & (customer['RENT VS. OWN'] == 'Own') & (customer['NUM HOUSEHOLD'] == 1)]

,REGION,RENT VS. OWN,NUM HOUSEHOLD,ANNUAL INCOME,TOTAL PURCHASES,NUM PURCHASES
CUST ID,,,,,,
1,North,Own,1,10K-25K,38,1
11,North,Own,1,50K-100K,21,4
348,North,Own,1,50K-100K,29,6
484,North,Own,1,25K-50K,61,6

In [18]:
# Q3. Show all information for customers who have at least 4 household members. 최소 4명의 가족구성원을 가진 고객들의 정보를 보여주시오.
customer[customer['NUM HOUSEHOLD'] >= 4]

,REGION,RENT VS. OWN,NUM HOUSEHOLD,ANNUAL INCOME,TOTAL PURCHASES,NUM PURCHASES
CUST ID,,,,,,
2,South,Own,4,100K+,30,4
4,West,Own,5,25K-50K,21,6
5,East,Own,6,50K-100K,35,7
8,West,Rent,4,25K-50K,25,6
9,North,Own,5,50K-100K,30,8
...,...,...,...,...,...,...
478,East,Own,4,50K-100K,59,7
479,North,Rent,5,100K+,60,8
480,West,Rent,7,50K-100K,68,9
486,East,Own,6,50K-100K,76,9
487,West,Own,4,50K-100K,98,2

In [24]:
# Q4. Show all information for customers who (a) have spent less than $20 or (b) more than $100. 20불미만 100불이상 소비한 고객들의 정보를 보여주시오.
customer[(customer['TOTAL PURCHASES'] < 20) | (customer['TOTAL PURCHASES'] > 100)]

,REGION,RENT VS. OWN,NUM HOUSEHOLD,ANNUAL INCOME,TOTAL PURCHASES,NUM PURCHASES
CUST ID,,,,,,
3,North,Rent,3,25K-50K,19,3
15,South,Rent,3,50K-100K,19,2
16,West,Own,5,25K-50K,19,6
17,North,Own,6,50K-100K,129,5
20,North,Rent,1,50K-100K,119,3
...,...,...,...,...,...,...
465,East,Own,4,25K-50K,119,7
466,South,Rent,5,50K-100K,129,2
468,North,Rent,2,50K-100K,119,3
469,North,Own,6,10K-25K,185,6
470,East,Own,3,100K+,119,9

In [25]:
# Q5. Provide a two-dimensional table using crosstab that counts the number of customers by the categories of REGION and RENT VS. OWN.
# 크로스탭을 이용하여 2차원 테이블을 만들되 지역과 렌트대소유에 따른 고객들의 수를 보여주시오.
pd.crosstab(customer['REGION'], customer['RENT VS. OWN'])

RENT VS. OWN  Own  Rent
REGION
East           82    66
North          63    62
South          51    47
West           66    50

In [26]:
# Q6. Provide a two-dimensional table using crosstab that sums the TOTAL PURCHASES of customers by the categories of REGION and RENT VS. OWN. 크로스탭을 이용하여 2차원 테이블을 만들되 지역과 렌트대소유에 따른 고객들의 총구매액의 합을 보여주시오.
pd.crosstab(customer['REGION'], customer['RENT VS. OWN'], values=customer['TOTAL PURCHASES'], aggfunc='sum')

RENT VS. OWN   Own  Rent
REGION
East          5793  4440
North         4260  4502
South         3326  3086
West          4335  3654

In [31]:
# Q7. Provide a query using Totals that counts the number of customers by the categories of REGION, RENT VS. OWN, and NUM HOUSEHOLD. 토탈스를 이용하여 쿼리를 만들되 지역, 렌트대소유, 가족구성원의 수에 따른 고객들의 수를 보여주시오.
customer.value_counts(['REGION','RENT VS. OWN','NUM HOUSEHOLD'])

REGION  RENT VS. OWN  NUM HOUSEHOLD
West    Own           4                20
East    Own           4                19
North   Rent          3                19
South   Own           4                17
East    Own           3                16
                      5                14
        Rent          3                14
North   Own           5                13
East    Own           6                13
West    Own           3                12
North   Own           2                12
West    Own           5                12
South   Rent          2                12
East    Rent          4                12
West    Own           6                11
North   Own           3                11
West    Rent          4                11
North   Rent          5                11
        Own           4                10
East    Rent          1                10
North   Own           6                10
East    Rent          5                10
South   Rent          4                10
North   Rent          2                 9
West    Rent          3                 9
South   Own           2                 9
West    Rent          5                 9
East    Rent          2                 8
West    Rent          6                 8
South   Rent          3                 8
        Own           3                 8
East    Own           2                 7
South   Own           5                 7
North   Rent          6                 7
South   Rent          5                 7
North   Rent          4                 7
East    Own           7                 7
                      1                 6
        Rent          6                 6
North   Rent          1                 6
East    Rent          7                 6
West    Rent          2                 6
South   Own           6                 5
West    Own           1                 5
South   Rent          6                 5
North   Own           1                 4
South   Rent          7                 4
West    Own           2                 4
        Rent          7                 4
North   Own           7                 3
        Rent          7                 3
South   Own           7                 3
West    Rent          1                 3
South   Own           1                 2
West    Own           7                 2
South   Rent          1                 1
Name: count, dtype: int64

In [ ]:
# 추가 쿼리